################
#              #
#   Package    #
# Installation #
#              #
################

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library(BiocManager)
BiocManager::install("GEOquery")
BiocManager::install("bumphunter")
BiocManager::install("minfi")
BiocManager::install("MethylAid")
BiocManager::install("BiocParallel")
BiocManager::install("minfiData")
BiocManager::install("sva")
BiocManager::install("stringi")
BiocManager::install("DMRcate")
BiocManager::install("FDb.InfiniumMethylation.hg19")
BiocManager::install("SummarizedExperiment")
BiocManager::install("S4Vectors")
BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19")
BiocManager::install("IlluminaHumanMethylation450kmanifest")
BiocManager::install("missMethyl")
BiocManager::install("Gviz")
BiocManager::install("limma")
BiocManager::install("MethylAid")
BiocManager::install("shinyMethyl")
library(minfi)
library(MethylAid)
library(BiocParallel)
library(GEOquery)
library(minfiData)
library(sva)
library(randomForest)
library(dplyr)
library(DMRcate)
library(SummarizedExperiment)
library(knitr)
library(limma)
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
library(IlluminaHumanMethylation450kmanifest)
library(missMethyl)
library(minfiData)
library(Gviz)
library(stringr)
library(parallel)
library(shinyMethyl)